# Generated by Django 4.0.4 on 2022-06-03 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_phone', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=155)),
                ('date_of_order', models.DateTimeField(auto_now=True)),
                ('status_of_order', models.CharField(choices=[('new', 'Новый'), ('issued', 'Оформлен'), ('cancelled', 'Отменен')], default='new', max_length=155)),
            ],
        ),
    ]
