# Generated by Django 4.0.4 on 2022-06-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backcall',
            name='type',
            field=models.CharField(default='Обратный звонок', max_length=255),
        ),
    ]
