# Generated by Django 4.0.4 on 2022-06-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_help_delete_answer_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagecolor',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product'),
        ),
    ]
