# Generated by Django 4.0.4 on 2022-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line_of_size',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
