# Generated by Django 4.0.4 on 2022-06-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productimagecolor_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line_of_size',
            field=models.IntegerField(),
        ),
    ]
