# Generated by Django 4.0.4 on 2022-06-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_line_of_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line_of_size',
            field=models.CharField(max_length=55),
        ),
    ]
