# Generated by Django 4.0.4 on 2022-06-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_favorite_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Избранные'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
