# Generated by Django 4.0.4 on 2022-06-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_line_of_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
