# Generated by Django 4.0.4 on 2022-06-07 07:54

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_new_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer_header', verbose_name='Логотип')),
                ('imformation', models.TextField(verbose_name='Информация')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SecondFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messen', models.CharField(choices=[('number', 'Номер'), ('email', 'Почта'), ('instagram', 'Instagram'), ('telegram', 'Телеграм'), ('whatsapp', 'WhatsApp')], max_length=155, verbose_name='Соцсеть')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('number', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='backcall',
            name='date_of_call',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='backcall',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='backcall',
            name='number_of_phone',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='help',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='help',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='oferro',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='oferro',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=150, verbose_name='Артикль'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.CharField(max_length=155, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Избранные'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Хит продаж'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line_of_size',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Линейка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=150, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='42-50', max_length=55, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='productimagecolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productimagecolor',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='field_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='slider_image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=155, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_order',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=155, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_phone',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_of_order',
            field=models.CharField(choices=[('new', 'Новый'), ('issued', 'Оформлен'), ('cancelled', 'Отменен')], default='new', max_length=155, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('second_footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='main.secondfooter')),
            ],
        ),
    ]
