# Generated by Django 4.0.4 on 2022-06-07 11:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_footer_secondfooter_alter_backcall_date_of_call_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondfooter',
            name='number',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='secondfooter',
            name='link',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
