# Generated by Django 4.0.4 on 2022-06-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_secondfooter_number_alter_aboutus_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='backcall',
            options={'verbose_name': 'Обратный звонок'},
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Наши преимущества'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Публичная оферта'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Публичная оферта'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='oferro',
            options={'verbose_name': 'Публичная оферта'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар'},
        ),
        migrations.AlterModelOptions(
            name='secondfooter',
            options={'verbose_name': 'Футер'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='main.product')),
            ],
        ),
    ]
