# Generated by Django 4.0.4 on 2022-06-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_aboutus_options_alter_backcall_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футер(первая вкладка)'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Помощь'},
        ),
        migrations.AlterModelOptions(
            name='imagehelp',
            options={'verbose_name': 'Фотография для помощи'},
        ),
        migrations.AlterModelOptions(
            name='secondfooter',
            options={'verbose_name': 'Футер(вторая вкладка)   '},
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
