# Generated by Django 4.0.4 on 2022-06-09 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_collection_options_alter_footer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_order',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='добавить время'),
        ),
    ]
