# Generated by Django 4.0.4 on 2022-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Новая цена'),
        ),
    ]
