# Generated by Django 4.0.4 on 2022-06-10 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_new_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='backcall',
            options={'verbose_name': 'Обратный звонок', 'verbose_name_plural': 'Обратный звонок'},
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Наши преимущества', 'verbose_name_plural': 'Наши преимущества'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекция'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футер(первая вкладка)', 'verbose_name_plural': 'Футер(первая вкладка)'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Помощь', 'verbose_name_plural': 'Помощь'},
        ),
        migrations.AlterModelOptions(
            name='imagehelp',
            options={'verbose_name': 'Фотография для помощи', 'verbose_name_plural': 'Фотография для помощи'},
        ),
        migrations.AlterModelOptions(
            name='oferro',
            options={'verbose_name': 'Публичная оферта', 'verbose_name_plural': 'Публичная оферта'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товар'},
        ),
        migrations.AlterModelOptions(
            name='secondfooter',
            options={'verbose_name': 'Футер(вторая вкладка)', 'verbose_name_plural': 'Футер(вторая вкладка)'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователь'},
        ),
        migrations.AlterField(
            model_name='backcall',
            name='date_of_call',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='добавить время'),
        ),
    ]
