# Generated by Django 4.0.4 on 2022-06-12 11:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_footer_delete_number_delete_secondfooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer_header', verbose_name='Логотип')),
                ('imformation', models.TextField(verbose_name='Информация')),
                ('number', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Футер(первая вкладка)',
                'verbose_name_plural': 'Футер(первая вкладка)',
            },
        ),
        migrations.CreateModel(
            name='SecondFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messen', models.CharField(choices=[('number', 'Номер'), ('email', 'Почта'), ('instagram', 'Instagram'), ('telegram', 'Телеграм'), ('whatsapp', 'WhatsApp')], max_length=155, verbose_name='Соцсеть')),
                ('link', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Футер(вторая вкладка)',
                'verbose_name_plural': 'Футер(вторая вкладка)',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('second_footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='main.secondfooter')),
            ],
        ),
    ]
