# Generated by Django 4.0.4 on 2022-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_footer_secondfooter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.CharField(max_length=150, verbose_name='Старая цена'),
        ),
    ]
