# Generated by Django 4.0.4 on 2022-06-12 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Кол-во')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='добавить время')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productimagecolor', verbose_name='цвет и фото')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзина',
                'unique_together': {('color',)},
            },
        ),
    ]
