# Generated by Django 4.0.4 on 2022-06-09 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_collection_options_alter_footer_options_and_more'),
        ('cart', '0002_alter_shoppingcart_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('user', 'products')},
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='color',
        ),
    ]
