# Generated by Django 4.0.4 on 2022-06-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_collection_options_alter_footer_options_and_more'),
        ('cart', '0003_alter_shoppingcart_unique_together_shoppingcart_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('products',)},
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
    ]
