# Generated by Django 4.0.4 on 2022-06-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_date_of_order'),
        ('cart', '0004_alter_shoppingcart_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='nums',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productimagecolor', verbose_name='цвет'),
        ),
    ]
