# Generated by Django 4.0.4 on 2022-06-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_date_of_order'),
        ('cart', '0005_remove_shoppingcart_nums_shoppingcart_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('color',)},
        ),
    ]
