# Generated by Django 4.0.4 on 2022-06-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_shoppingcart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
