# Generated by Django 4.0.4 on 2022-06-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_shoppingcart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
