# Generated by Django 4.0.4 on 2022-06-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set(),
        ),
    ]
