# Generated by Django 4.0.4 on 2022-06-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_product_amount_alter_product_old_price'),
        ('cart', '0010_alter_shoppingcart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productimagecolor', verbose_name='цвет и фото'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('color',)},
        ),
    ]
