# Generated by Django 4.0.4 on 2022-06-12 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_order', models.PositiveIntegerField(default=0)),
                ('total_price', models.CharField(max_length=55)),
                ('price_with_discount', models.CharField(max_length=55)),
                ('discount', models.CharField(max_length=10)),
                ('quantity_of_products', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
            },
        ),
    ]
