# Generated by Django 4.0.4 on 2022-06-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('order', '0008_alter_order_number_of_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='cart.shoppingcart'),
        ),
    ]
